apiVersion: v1
kind: Service
metadata:
  name: totem-express-users-svc
spec:
  selector:
    app: totem-express-users
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
  type: LoadBalancer